package com.resumatch.service;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.List;
import com.itextpdf.layout.element.ListItem;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.resumatch.model.AnalysisResult;
import com.resumatch.model.AnalysisStatus;
import com.resumatch.model.ImprovedResume;
import com.resumatch.model.User;
import com.resumatch.repository.ImprovedResumeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;

@Service
@RequiredArgsConstructor
@Slf4j
public class ResumePdfService {

    private final ImprovedResumeRepository improvedResumeRepository;

    /**
     * Generate a professional A4 Resume PDF.
     * Synchronizes with AI suggestions if the latest analysis is APPLIED.
     */
    public byte[] generateResumePdf(User user, AnalysisResult lastAnalysis) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            PdfDocument pdfDoc = new PdfDocument(new PdfWriter(baos));
            Document document = new Document(pdfDoc, PageSize.A4);
            document.setMargins(50, 50, 50, 50);

            PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont normal = PdfFontFactory.createFont(StandardFonts.HELVETICA);
            DeviceRgb darkBlue = new DeviceRgb(20, 30, 70);

            // ── HEADER ──
            document.add(new Paragraph(user.getName() != null ? user.getName().toUpperCase() : "CANDIDATE NAME")
                    .setFont(bold).setFontSize(24).setFontColor(darkBlue).setTextAlignment(TextAlignment.CENTER));
            
            document.add(new Paragraph(user.getEmail() + " | " + (user.getIndustry() != null ? user.getIndustry() : "Technology"))
                    .setFont(normal).setFontSize(10).setTextAlignment(TextAlignment.CENTER).setMarginBottom(20));

            SolidLine line = new SolidLine(1f);
            line.setColor(new DeviceRgb(200, 200, 200));
            document.add(new LineSeparator(line).setMarginBottom(15));

            // Determine if we should use AI Improved content
            
            // ── PROFESSIONAL SUMMARY ──
            document.add(new Paragraph("PROFESSIONAL SUMMARY").setFont(bold).setFontSize(14).setMarginBottom(5));
            String summary = "";
            if (lastAnalysis != null && lastAnalysis.getStatus() == AnalysisStatus.APPLIED) {
                summary = lastAnalysis.getImprovedSummary();
            } else {
                summary = extractSection(user.getLastParsedResume(), "SUMMARY");
            }
            document.add(new Paragraph(summary).setFont(normal).setFontSize(11).setMultipliedLeading(1.4f).setMarginBottom(15));

            // ── EXPERIENCE ──
            document.add(new Paragraph("EXPERIENCE").setFont(bold).setFontSize(14).setMarginBottom(5));
            java.util.List<String> bullets = new ArrayList<>();
            
            if (lastAnalysis != null && lastAnalysis.getStatus() == AnalysisStatus.APPLIED) {
                java.util.List<ImprovedResume> improvedBullets = improvedResumeRepository.findByAnalysisResultId(lastAnalysis.getId());
                for (ImprovedResume ir : improvedBullets) {
                    if ("Experience Bullet".equals(ir.getSectionName())) {
                        bullets.add(ir.getAiImprovedText());
                    }
                }
            }
            
            if (bullets.isEmpty()) {
                // Fallback: extract bullets from raw text if possible, or use raw text
                bullets = extractBullets(user.getLastParsedResume());
            }

            List list = new List().setSymbolIndent(12).setListSymbol("• ");
            for (String b : bullets) {
                ListItem li = new ListItem();
                li.add(new Paragraph(b).setFont(normal).setFontSize(11).setMultipliedLeading(1.3f));
                list.add(li);
            }
            document.add(list.setMarginBottom(20));

            // Footer
            document.add(new LineSeparator(line).setMarginTop(20));
            document.add(new Paragraph("Generated by ResuMatch AI — The Digital Curator")
                    .setFont(normal).setFontSize(8).setTextAlignment(TextAlignment.CENTER).setFontColor(new DeviceRgb(180,180,180)));

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            log.error("Resume PDF generation failed: {}", e.getMessage());
            throw new RuntimeException("Failed to generate Resume PDF", e);
        }
    }

    private String extractSection(String text, String sectionName) {
        if (text == null || text.isBlank()) return "Professional with background in " + sectionName;
        // Basic heuristic extraction
        return text.split("\n")[0]; 
    }

    private java.util.List<String> extractBullets(String text) {
        java.util.List<String> bullets = new ArrayList<>();
        if (text == null) return bullets;
        String[] lines = text.split("\n");
        for (String line : lines) {
            if (line.trim().startsWith("•") || line.trim().startsWith("-")) {
                bullets.add(line.trim().substring(1).trim());
            }
        }
        if (bullets.isEmpty()) bullets.add(text.length() > 200 ? text.substring(0, 200) + "..." : text);
        return bullets;
    }
}
